name: "spetclinic"
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: false
        default: 'dev'
        type: choice
        options:
        - dev
        - staging
        - prod
      skip_tests:
        description: 'Skip tests'
        required: false
        default: false
        type: boolean
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: main
          
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
          
      - name: Apply code formatting
        run: mvn spring-javaformat:apply
          
      - name: Build and test project
        run: |
          mvn -v
          if [ "${{ github.event.inputs.skip_tests }}" = "true" ]; then
            echo "Skipping tests as requested"
            mvn clean package -DskipTests=true -Dcheckstyle.skip=true
          else
            echo "Running tests"
            mvn clean package -Dcheckstyle.skip=true
          fi
          
      - name: Upload build artifacts
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: spetclinic-${{ github.event.inputs.environment }}-${{ github.run_number }}
          path: target/*.jar
          retention-days: 30
          
      - name: Send failure notification
        if: failure()
        run: |
          payload=$(cat <<EOF
          {
            "platform": "github",
            "job": "${{ github.workflow }}",
            "build": "${{ github.run_number }}",
            "result": "FAILURE",
            "buildUrl": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
            "consoleUrl": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}",
            "timestamp": "$(date -u '+%Y-%m-%d %H:%M:%S UTC')",
            "repository": "${{ github.repository }}",
            "branch": "${{ github.ref_name }}",
            "commit": "${{ github.sha }}",
            "trigger": "${{ github.event_name }}",
            "environment": "${{ github.event.inputs.environment || 'dev' }}"
          }
          EOF
          )
          
          curl -X POST \
            -H "Content-Type: application/json" \
            -H "Accept: application/json" \
            --max-time 30 \
            --data "$payload" \
            "${{ secrets.N8N_URL }}" || echo "Webhook notification failed (non-blocking)"
